image: hugomods/hugo:exts

variables:
  HUGO_ENV: production
  LC_ALL: C.UTF-8

stages:
  - update
  - deploy

update-dependencies:
  stage: update
  image:
    name: ghcr.io/updatecli/updatecli:latest
    entrypoint: [""]
  variables:
    UPDATECLI_GITLAB_TOKEN: $GITLAB_TOKEN
    UPDATECLI_GITLAB_USER: $GITLAB_USER
  script:
    - /updatecli apply --config updatecli.d/
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

pages:
  stage: deploy
  before_script:
    - apk add --no-cache lftp ruby ruby-dev build-base
    - gem install asciidoctor rouge --no-document
  script:
    - hugo --minify -d public
    - mkdir -p ~/.lftp/ && echo "set ssl:verify-certificate no" >> ~/.lftp/rc
    - lftp -e "open $FTP_SERVER; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ -x default_index.html --reverse --verbose --delete public $DESTINATION_FOLDER; bye"
  artifacts:
    paths:
      - public
